/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.resource;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.example.fowlerdsl.statemachine.Command;
import org.eclipse.xtext.example.fowlerdsl.statemachine.Event;
import org.eclipse.xtext.example.fowlerdsl.statemachine.State;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.resource.impl.DefaultResourceDescriptionStrategy;
import org.eclipse.xtext.util.IAcceptor;

public class StatemachineAbstractResourceDescriptionStrategy extends DefaultResourceDescriptionStrategy {
	public boolean createEObjectDescriptions(EObject eObject, IAcceptor<IEObjectDescription> acceptor) {
		if(eObject instanceof Event) {
			return createEObjectDescriptionsForEvent(eObject, acceptor);
		}
		if(eObject instanceof Command) {
			return createEObjectDescriptionsForCommand(eObject, acceptor);
		}
		if(eObject instanceof State) {
			return createEObjectDescriptionsForState(eObject, acceptor);
		}
		return true;
	}

	protected boolean createEObjectDescriptionsForEvent(EObject eObject, IAcceptor<IEObjectDescription> acceptor) {
		return super.createEObjectDescriptions(eObject, acceptor);
	}
	protected boolean createEObjectDescriptionsForCommand(EObject eObject, IAcceptor<IEObjectDescription> acceptor) {
		return super.createEObjectDescriptions(eObject, acceptor);
	}
	protected boolean createEObjectDescriptionsForState(EObject eObject, IAcceptor<IEObjectDescription> acceptor) {
		return super.createEObjectDescriptions(eObject, acceptor);
	}
}
