/**
 * generated by Xtext
 */
package org.eclipse.xtext.example.domainmodel.tests;

import org.eclipse.xtext.example.domainmodel.domainmodel.DomainModel;
import org.eclipse.xtext.example.domainmodel.tests.DomainmodelInjectorProvider;
import org.eclipse.xtext.xbase.lib.Extension;

/* @RunWith(/* name is null */)
@InjectWith(DomainmodelInjectorProvider.class) */@SuppressWarnings("all")
public class DomainmodelParsingTest {
  /* @Inject */@Extension
  private /* ParseHelper<DomainModel> */Object _parseHelper;
  
  /* @Inject */@Extension
  private /* ValidationTestHelper */Object _validationTestHelper;
  
  /* @Inject */@Extension
  private /* IJvmModelAssociations */Object _iJvmModelAssociations;
  
  /* @Test
   */public void testParsing() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field parse is undefined for the type CharSequence"
      + "\nThe method or field Assert is undefined"
      + "\nThe method getElements() is undefined for the type PackageDeclaration"
      + "\nThe method or field Assert is undefined"
      + "\nThe method getFeatures() is undefined for the type Entity"
      + "\nThe method or field Assert is undefined"
      + "\nThe method or field Assert is undefined"
      + "\nThe method getType() is undefined for the type Property"
      + "\ngetElements cannot be resolved"
      + "\nget cannot be resolved"
      + "\nassertEquals cannot be resolved"
      + "\nget cannot be resolved"
      + "\nassertEquals cannot be resolved"
      + "\nget cannot be resolved"
      + "\nassertEquals cannot be resolved"
      + "\nassertEquals cannot be resolved"
      + "\ngetIdentifier cannot be resolved");
  }
  
  /* @Test
   */public void testJvmTypeReferencesValidator() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field parse is undefined for the type CharSequence"
      + "\nThe method or field TypesPackage is undefined"
      + "\nThe method or field IssueCodes is undefined"
      + "\nassertError cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nJVM_TYPE_REFERENCE cannot be resolved"
      + "\nINVALID_USE_OF_TYPE cannot be resolved");
  }
  
  /* @Test
   */public void testParsingAndLinking() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field parse is undefined for the type CharSequence"
      + "\nassertNoErrors cannot be resolved");
  }
  
  /* @Test
   */public void testParsingAndLinkingWithImports() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field parse is undefined for the type CharSequence"
      + "\nassertNoErrors cannot be resolved");
  }
  
  /* @Test
   */public void testReturnTypeInference() {
    throw new Error("Unresolved compilation problems:"
      + "\nJvmOperation cannot be resolved to a type."
      + "\nThe method or field parse is undefined for the type CharSequence"
      + "\nThe method or field elements is undefined for the type PackageDeclaration"
      + "\nThe method or field features is undefined for the type Entity"
      + "\nThe method or field jvmElements is undefined for the type Operation"
      + "\nThe method or field Assert is undefined"
      + "\nelements cannot be resolved"
      + "\nhead cannot be resolved"
      + "\nhead cannot be resolved"
      + "\nlast cannot be resolved"
      + "\nhead cannot be resolved"
      + "\nassertEquals cannot be resolved"
      + "\nreturnType cannot be resolved"
      + "\nsimpleName cannot be resolved");
  }
}
