/**
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.ui.wizard;

import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.ui.wizard.template.AbstractFileTemplate;
import org.eclipse.xtext.ui.wizard.template.FileTemplate;
import org.eclipse.xtext.ui.wizard.template.IFileGenerator;

@FileTemplate(label = "MrsGrantsSecretCompartments", icon = "file_template.png", description = "Mrs Grants Secret Compartments.")
@SuppressWarnings("all")
public final class MrsGrantsSecretCompartments extends AbstractFileTemplate {
  @Override
  public void generateFiles(final IFileGenerator generator) {
    StringConcatenation _builder = new StringConcatenation();
    String _folder = this.getFolder();
    _builder.append(_folder);
    _builder.append("/");
    String _name = this.getName();
    _builder.append(_name);
    _builder.append(".statemachine");
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("doorClosed\tD1CL");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("drawOpened\tD2OP");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("lightOn\t\tL1ON");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("doorOpened\tD1OP");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("panelClosed PNCL");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("resetEvents");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("doorClosed");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("commands");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("unlockPanel PNUL");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("lockPanel\tPNLK");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("lockDoor\tD1LK");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("unlockDoor\tD1UL");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("state idle");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("actions {unlockDoor lockPanel}");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("doorClosed => active");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("state active");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("drawOpened \t=> waitingForLight");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("lightOn\t\t=> waitingForDraw");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("state waitingForLight");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("lightOn => unlockedPanel");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("state waitingForDraw");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("drawOpened => unlockedPanel");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("state unlockedPanel");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("actions {unlockPanel lockDoor}");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("panelClosed => idle");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    generator.generate(_builder, _builder_1);
  }
}
