/**
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.ui.wizard;

import com.google.common.collect.Iterables;
import java.util.Collections;
import java.util.List;
import org.eclipse.core.runtime.IStatus;
import org.eclipse.core.runtime.Status;
import org.eclipse.jdt.core.JavaCore;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.ui.XtextProjectHelper;
import org.eclipse.xtext.ui.util.PluginProjectFactory;
import org.eclipse.xtext.ui.wizard.template.AbstractProjectTemplate;
import org.eclipse.xtext.ui.wizard.template.BooleanTemplateVariable;
import org.eclipse.xtext.ui.wizard.template.GroupTemplateVariable;
import org.eclipse.xtext.ui.wizard.template.IProjectGenerator;
import org.eclipse.xtext.ui.wizard.template.ProjectTemplate;
import org.eclipse.xtext.ui.wizard.template.StringTemplateVariable;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.ObjectExtensions;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;

@ProjectTemplate(label = "Statemachine example", icon = "project_template.png", description = "<p><b>Simple statemachine example</b></p>\n<p>This is a project wizard to create a simple statemachine example.</p>")
@SuppressWarnings("all")
public final class SimpleStatemachineExampleWithFile extends AbstractProjectTemplate {
  private final BooleanTemplateVariable advanced = this.check("Advanced:", false);
  
  private final GroupTemplateVariable advancedGroup = this.group("Properties");
  
  private final BooleanTemplateVariable generateFile = this.check("Generate example file?", true, this.advancedGroup);
  
  private final StringTemplateVariable name = this.text("Custom State:", "MyCustomState", "The name of a custom state", this.advancedGroup);
  
  private final StringTemplateVariable path = this.text("Package:", "statemachine", "The package path to place the files in", this.advancedGroup);
  
  @Override
  protected void updateVariables() {
    this.name.setEnabled((this.advanced.getValue() && this.generateFile.getValue()));
    this.path.setEnabled((this.advanced.getValue() && this.generateFile.getValue()));
    boolean _value = this.advanced.getValue();
    boolean _not = (!_value);
    if (_not) {
      this.name.setValue("Xtext");
      this.path.setValue("statemachine");
    }
  }
  
  @Override
  protected IStatus validate() {
    Status _xifexpression = null;
    boolean _matches = this.path.getValue().matches("[a-z][a-z0-9_]*(/[a-z][a-z0-9_]*)*");
    if (_matches) {
      _xifexpression = null;
    } else {
      _xifexpression = new Status(IStatus.ERROR, "Wizard", (("\'" + this.path) + "\' is not a valid package name"));
    }
    return _xifexpression;
  }
  
  @Override
  public void generateProjects(final IProjectGenerator generator) {
    PluginProjectFactory _pluginProjectFactory = new PluginProjectFactory();
    final Procedure1<PluginProjectFactory> _function = (PluginProjectFactory it) -> {
      it.setProjectName(this.getProjectInfo().getProjectName());
      it.setLocation(this.getProjectInfo().getLocationPath());
      List<String> _projectNatures = it.getProjectNatures();
      Iterables.<String>addAll(_projectNatures, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList(JavaCore.NATURE_ID, "org.eclipse.pde.PluginNature", XtextProjectHelper.NATURE_ID)));
      List<String> _builderIds = it.getBuilderIds();
      _builderIds.add(JavaCore.BUILDER_ID);
      List<String> _folders = it.getFolders();
      _folders.add("src");
      boolean _value = this.generateFile.getValue();
      if (_value) {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("src/");
        _builder.append(this.path);
        _builder.append("/Model.statemachine");
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.newLine();
        _builder_1.append("events");
        _builder_1.newLine();
        _builder_1.append("\t");
        _builder_1.append("doorClosed\tD1CL");
        _builder_1.newLine();
        _builder_1.append("\t");
        _builder_1.append("drawOpened\tD2OP");
        _builder_1.newLine();
        _builder_1.append("\t");
        _builder_1.append("lightOn\t\tL1ON");
        _builder_1.newLine();
        _builder_1.append("\t");
        _builder_1.append("doorOpened\tD1OP");
        _builder_1.newLine();
        _builder_1.append("\t");
        _builder_1.append("panelClosed PNCL");
        _builder_1.newLine();
        _builder_1.append("end");
        _builder_1.newLine();
        _builder_1.newLine();
        _builder_1.newLine();
        _builder_1.append("state ");
        _builder_1.append(this.name);
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("\t");
        _builder_1.append("// Custom State");
        _builder_1.newLine();
        _builder_1.append("end");
        _builder_1.newLine();
        this.addFile(it, _builder, _builder_1);
      }
    };
    PluginProjectFactory _doubleArrow = ObjectExtensions.<PluginProjectFactory>operator_doubleArrow(_pluginProjectFactory, _function);
    generator.generate(_doubleArrow);
  }
}
