/**
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.ui.wizard;

import org.eclipse.xtext.example.fowlerdsl.ui.wizard.SimpleStatemachineExampleWithFile;
import org.eclipse.xtext.ui.wizard.template.AbstractProjectTemplate;
import org.eclipse.xtext.ui.wizard.template.IProjectTemplateProvider;

/**
 * Create a list with all project templates to be shown in the template new project wizard.
 * 
 * Each template is able to generate one or more projects. Each project can be configured such that any number of files are included.
 */
@SuppressWarnings("all")
public class StatemachineProjectTemplateProvider implements IProjectTemplateProvider {
  @Override
  public AbstractProjectTemplate[] getProjectTemplates() {
    SimpleStatemachineExampleWithFile _simpleStatemachineExampleWithFile = new SimpleStatemachineExampleWithFile();
    return new AbstractProjectTemplate[] { _simpleStatemachineExampleWithFile };
  }
}
