/**
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.ui.wizard;

import org.eclipse.xtext.example.fowlerdsl.ui.wizard.HelloWorldFile;
import org.eclipse.xtext.example.fowlerdsl.ui.wizard.MrsGrantsSecretCompartments;
import org.eclipse.xtext.ui.wizard.template.AbstractFileTemplate;
import org.eclipse.xtext.ui.wizard.template.IFileTemplateProvider;

/**
 * Create a list with all file templates to be shown in the template new file wizard.
 * 
 * Each template is able to generate one or more files.
 */
@SuppressWarnings("all")
public class StatemachineFileTemplateProvider implements IFileTemplateProvider {
  @Override
  public AbstractFileTemplate[] getFileTemplates() {
    HelloWorldFile _helloWorldFile = new HelloWorldFile();
    MrsGrantsSecretCompartments _mrsGrantsSecretCompartments = new MrsGrantsSecretCompartments();
    return new AbstractFileTemplate[] { _helloWorldFile, _mrsGrantsSecretCompartments };
  }
}
