/**
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.validation;

import org.eclipse.xtext.example.fowlerdsl.validation.AbstractStatemachineValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class StatemachineValidator extends AbstractStatemachineValidator {
}
